<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="TelemetryFlatfieldLeds" Id="{d9a8b24e-d630-47bd-a23c-acf6b1d0d0a8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TelemetryFlatfieldLeds EXTENDS SM_TelemetryFlatfieldLeds
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_TelemetryTemperatures : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>