<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.36">
  <POU Name="TelemetryRelativeHumidities" Id="{a1d3a85c-8191-4d82-831f-93d259e479d6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TelemetryRelativeHumidities EXTENDS SM_TelemetryRelativeHumidities
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_TelemetryRelativeHumidities : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^(config := config);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>