<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="DEG_TO_RAD" Id="{633938d1-ee6d-45ac-aed6-d1f11529bcff}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION DEG_TO_RAD : LREAL
VAR_INPUT
    degrees : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[DEG_TO_RAD := degrees / 180.0 * PI;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>