<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="RAD_TO_HOUR" Id="{4c241ac3-9c1a-485d-b8de-b30ff65ac587}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION RAD_TO_HOUR : LREAL
VAR_INPUT
    rad : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[RAD_TO_HOUR := rad * 12.0 / PI;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>