<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="CoverIO" Id="{7179e359-56e0-423b-b637-b5905b503c88}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CoverIO EXTENDS SM_CoverIO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

// do stuff

//SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>