<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="HydraulicsPumpsGroupIO" Id="{bad74441-994e-487f-abea-96b273d9c376}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HydraulicsPumpsGroupIO EXTENDS SM_HydraulicsPumpsGroupIO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>