///////////////////////////////////////////////////////////////////////////////
// SlalibClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "SlalibClassFactory.h"
#include "SlalibServices.h"
#include "SlalibVersion.h"
#include "SlaPointing.h"

BEGIN_CLASS_MAP(CSlalibClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_SlalibCSlaPointing, SRVNAME_SLALIB "!CSlaPointing", CSlaPointing)
///</AutoGeneratedContent>
END_CLASS_MAP()

CSlalibClassFactory::CSlalibClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_SLALIB)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Slalib));
#endif //defined(TCDBG_UNIT_VERSION)
}

