<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="M1M2IO" Id="{ccc8ad36-63ff-4126-9530-fea3e2775d63}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK M1M2IO EXTENDS SM_M1M2IO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_M1M2IO : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>