<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="SafetyHydraulicsAndSafetyIO" Id="{fafd51c0-7c66-4aff-89a1-c11a6e3c5ddf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SafetyHydraulicsAndSafetyIO EXTENDS SM_SafetyHydraulicsAndSafetyIO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

// do stuff

//SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>