<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="CANopenBusWidget" Id="{6ab8ccc3-73bc-4670-8f1e-59fe5cca5ff9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CANopenBusWidget
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	actualStatus : StatusWidget;
END_VAR
VAR_IN_OUT
	ref : CANopenBus;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[actualStatus(text := ref.actualStatus, color := HealthToColor(ref.statuses.healthStatus));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>