<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="SubSubSystemButtonWidget" Id="{9e9c5463-4f44-4f57-836e-ed90d1a381d9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK SubSubSystemButtonWidget EXTENDS SubSystemButtonWidget
VAR_INPUT
END_VAR
VAR_IN_OUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^(activeTab := activeTab);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>