<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="Current" Id="{486bf2a4-522c-4124-b0bc-3cc8c92a11ab}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Current EXTENDS SM_Current
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>