<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="Force" Id="{0ce24775-63b0-4fba-9d0b-d221aace8cd3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Force EXTENDS SM_Force
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>