<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="GForce" Id="{5ca09db4-46a3-4752-ba1d-2432d0771d54}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK GForce EXTENDS SM_GForce
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>