<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="LinearAxis" Id="{eb39d377-f253-4d60-9db3-aa3565f100db}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LinearAxis EXTENDS SM_LinearAxis;
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_LinearAxis : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>