<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="LinearPosition" Id="{90c58a97-434a-4c49-b49b-b7dec7933b73}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK LinearPosition EXTENDS SM_LinearPosition
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_LinearPosition : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

// do stuff

//SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>