<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="Pressure" Id="{ca6f748a-613d-4cab-83f7-833d3799ddc9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Pressure EXTENDS SM_Pressure
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_Pressure : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>