<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="QuantityValue" Id="{6d58ff80-1670-42e4-9c84-7aa13490a2b2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK QuantityValue EXTENDS SM_QuantityValue
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

// do stuff

SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>