<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="Temperature" Id="{5f3a6710-e2e1-44ea-8138-203001a209df}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Temperature EXTENDS SM_Temperature
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_Temperature : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>