<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="Torque" Id="{5eda0452-c252-4ade-95e5-c02bc5dcc087}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Torque EXTENDS SM_Torque
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>