<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.2">
  <POU Name="Voltage" Id="{def5fc12-e190-4589-a260-3267dfd7fe2e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Voltage EXTENDS SM_Voltage
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>