<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4019.2">
  <POU Name="AxesFeedback" Id="{5f29066f-bccb-4802-b6c3-b32cfba28831}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AxesFeedback EXTENDS SM_AxesFeedback
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>