<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="ServicesTimingIO" Id="{b0941309-43ee-463d-a122-ae4cf1c5d03b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ServicesTimingIO EXTENDS SM_ServicesTimingIO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    _testVar_TimingIO : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

// do stuff

//SUPER^();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>